language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

env:
  - CXX=clang++-3.5 CXX_host=clang++-3.5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - binutils
    - clang-3.5

install: npm install --clang=1

after_script:
  - npm run-script packageBinary
  - npm run-script publishBinary