language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

env:
  - CXX=g++-4.8
  - CXX=g++-4.6

matrix:
  exclude:
    - node_js: 'iojs'
      env: CXX=g++-4.6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

after_script:
  - npm run-script packageBinary
  - npm run-script publishBinary