language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.12'
  - 'iojs'

env:
  - CXX=clang++-3.5

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.5

after_script:
  - npm run-script packageBinary
  - npm run-script publishBinary